//
// Created by patSurface on 2018-11-26.
//

#ifndef ASSIGNMENT_A2_PETTERJ123_POLYGON_H
#define ASSIGNMENT_A2_PETTERJ123_POLYGON_H

class Polygon {

};


#endif //ASSIGNMENT_A2_PETTERJ123_POLYGON_H
